# Generated by Django 5.0.2 on 2024-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_order_remove_section_next_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
