# Generated by Django 5.0.2 on 2024-03-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_choices_alter_question_text_delete_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveysection',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='surveysection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='surveysection',
            name='has_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveysection',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.survey'),
        ),
        migrations.AlterUniqueTogether(
            name='surveysection',
            unique_together={('survey', 'section', 'order')},
        ),
    ]
