# Generated by Django 5.0.2 on 2024-03-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_question_choices_question_choice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Обязательный вопрос'),
        ),
    ]
